import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Script
        src="https://accounts.google.com/gsi/client"
        strategy="afterInteractive"
        async
        defer
      />

        <nav className="fixed top-0 left-0 w-full flex justify-between items-center px-6 py-4 border-b border-gray-200 bg-black">
          <h1 className="text-xl font-semibold">ShareTea</h1>
          <ul className="flex gap-6 text-sm font-medium">
            <li><a href="/" className="hover:underline">Home</a></li>
            <li><a href="/order" className="hover:underline">Order</a></li>
            <li><a href="/dashboard" className="hover:underline">Dashboard</a></li>
            <li><a href="/login" className="hover:underline">Login</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
